#!/usr/bin/env bash
# Script that transfer a file from the client to a server
# The script accepts 4 parameters:
# 1 - path to the file to be transferred
# 2 - IP of server to transfer file to
# 3 - username of scp
# 4 - path to SSH private key that scp will use

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	PATH_TO_FILE=$1
	IP=$2
	USERNAME=$3
	PATH_TO_SSH_KEY=$4

	scp -o StrictHostKeyCheicking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/
fi
