#!/usr/bin/env bash
# script that installs nginx and configures it on a remote server
# and also redirect the /redirect_me page of nginx server
# redirection will be '301 Moved Permanently'
# server to be restarted to update changes

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
service nginx start
