#!/usr/bin/env bash
# a script that Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers

echo "
frontend lb
        bind *:80
        mode http
        default_backend webservers

backend webservers
        balance roundrobin
        server 162801-web-01 52.86.198.91:80 check
        server 162801-web-02 52.207.52.133:80 check   
" >> /etc/haproxy/haproxy.cfg

service haproxy start
