#!/usr/bin/env bash
# script that configures an Nginx server to listen on port 80.
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
