#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely
# with a sleep mode
# & I am invincible!!! when receiving a SIGTERM signal

for (( i=0; i>=0; i++ ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
